load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library", "scala_specs2_junit_test")

scala_binary(
    name = "day12",
    srcs = glob(["*.scala"]),
    main_class = "jef5ez.advent.Day12",
    deps = ["//src/main/resources:advent-inputs"],
)
